### ISSUE TITLE
Looks like the image loading of the pizza logo isn't working. any idea how to fix it?

### ISSUE THREAD

**Issue by yarneo-doordash** [1998code/iOS16-Live-Activities#14]
**Describe the bug**
Looks like the image loading of the pizza logo isn't working. any idea how to fix it?

**To Reproduce**
Try making the logo show up. instead the entire live activity refuses to work.

**Comment by 1998code** [comment]
@yarneo-doordash Fixed. It seems the image size is too big.

[e6ac601](https://github.com/1998code/iOS16-Live-Activities/commit/e6ac60131473463662f773bdd86f0db50acac810)

![CleanShot 2023-06-15 at 04 45 07@2x](https://github.com/1998code/iOS16-Live-Activities/assets/54872601/454e7530-66f0-4309-bc16-f00bb3a0c66e)
