### ISSUE TITLE
How you preview the live activity UI on development?

### ISSUE THREAD

**Issue by Yggdrasilqh** [1998code/iOS16-Live-Activities#2]
It's a helpful and amazing demo!

but I don't see any preview code on this demo. I wanna know how to preview the activity widget use the `PreviewProvider` ? or you just run entire app to preview the UI?

```swift
struct live_activities_Previews: PreviewProvider {
    static var previews: some View {
        live_activitiesEntryView(context: !how to create this!)
            .previewContext(WidgetPreviewContext(family: .systemSmall))
    }
}
```

Thanks!

**Comment by 1998code** [comment]
Hi. I haven't yet seen how to preview the live activities widget in Apple Developer Documentation.
So, I run the app to preview the UI.

Or you may preview the widget design first, then copy the code back to the Live Widget(s).
<img width="1271" alt="CleanShot 2022-07-30 at 23 46 10@2x" src="https://user-images.githubusercontent.com/54872601/181924702-e6149d23-a1ad-4b80-935c-cb438bcb997a.png">

Hope help :)

**Comment by Yggdrasilqh** [comment]
> Hi. I cannot find how to preview the live activities widget in Apple Developer Documentation. The thing is still in beta. So, I simply run the app to preview the UI.
> 
> Or you may preview the widget design first, then copy the code back to the Live Widget(s). <img alt="CleanShot 2022-07-30 at 23 46 10@2x" width="1271" src="https://user-images.githubusercontent.com/54872601/181924702-e6149d23-a1ad-4b80-935c-cb438bcb997a.png">
> 
> Hope help :) @Yggdrasilqh

Oh, that's a good idea!
thanks for your reply. have a good day!
