### ISSUE TITLE
Not found in scope

### ISSUE THREAD

**Issue by alphaSoft99** [1998code/iOS16-Live-Activities#3]
Hi, thanks that, your code works, but it does not work  in my project, how i can solve this?
<img width="452" alt="Screenshot 2022-08-08 at 17 49 04" src="https://user-images.githubusercontent.com/48862051/183421800-0b2e2b03-4108-4ec9-9a4a-235ceb7ec5d7.png">

<img width="694" alt="Screenshot 2022-08-08 at 17 45 02" src="https://user-images.githubusercontent.com/48862051/183421458-1991df0b-1683-4f18-92ed-85ea7c68f2bc.png">
<img width="1074" alt="Screenshot 2022-08-08 at 17 47 59" src="https://user-images.githubusercontent.com/48862051/183421609-15a83d6f-d2c1-4840-a895-996588568c61.png">

**Comment by 1998code** [comment]
Hi. Please check the target membership.

1. Go to `ActivityAttributes.swift`
<img width="240" alt="CleanShot 2022-08-08 at 21 43 04@2x" src="https://user-images.githubusercontent.com/54872601/183432300-3aba625c-eddf-416d-b874-2528ca6f6a13.png">

2. Be sure it targeted `WidgetDemoExtension` too.
<img width="263" alt="CleanShot 2022-08-08 at 21 44 28@2x" src="https://user-images.githubusercontent.com/54872601/183432624-5449568d-5027-4047-934b-088d6df29a45.png">

Let me know if it works :)

**Comment by alphaSoft99** [comment]
Thanks, it works. And when you integrate widget with remote notification (fcm) ?

**Comment by 1998code** [comment]
@alphaSoft99 
Please see if this pull request can answer your question.
https://github.com/1998code/iOS16-Live-Activities/issues/8#issuecomment-1293176462
