### ISSUE TITLE
请问怎么获得iOS 16 beta 4* ... iOS 16.1 beta 1

### ISSUE THREAD

**Issue by borischou** [1998code/iOS16-Live-Activities#4]
请问从哪里可以下载？

谢谢！

**Comment by 1998code** [comment]
Hi @borischou , you can download the beta via https://developer.apple.com/download 🙂

**Comment by borischou** [comment]
Hi, @1998code, sorry but I meant the image for iOS simulator, not the device support.

**Comment by 1998code** [comment]
@borischou oic.
The simulator is included within Xcode. Please find below:
https://developer.apple.com/xcode/resources/

**Comment by borischou** [comment]
Thanks, I've found what I need. Thank you for your time.
