### ISSUE TITLE
Is Dynamic Island Available with iphone 14 pro simulator?

### ISSUE THREAD

**Issue by akshay2792** [1998code/iOS16-Live-Activities#6]
Hi @1998code, Is Dynamic Island Available with iphone 14 pro simulator?

**Comment by 1998code** [comment]
Yes. @akshay2792 
<img width="548" alt="CleanShot 2022-09-21 at 16 26 19@2x" src="https://user-images.githubusercontent.com/54872601/191454870-1b6e1fcb-45f7-4378-b4ef-e5da16fabcf3.png">

**Comment by 1998code** [comment]
Hi @akshay2792 please download Xcode-beta via https://developer.apple.com/download/applications/
The minimum environment is Xcode 14.1 beta 1.

**Comment by 1998code** [comment]
<img width="327" alt="CleanShot 2022-09-21 at 16 54 33@2x" src="https://user-images.githubusercontent.com/54872601/191460919-9f228969-7ef7-4014-b4e5-ee66ba469251.png">

Refer to the Apple Developer Website.
